name: Break glass
on:
  issue_comment:
    types:
      - created

jobs:
  breakglass:
    permissions: write-all
    if: ${{ github.event.comment.body == '/breakglass' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Pull Request
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ssh-key: ${{ secrets.BREAKGLASS_SSH_KEY }}
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Announce the imminent merge
        run: |
          gh pr comment ${{ github.event.issue.number }} -b "Breaking glass and merging this PR immediately"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up the SSH key
        run: |
          echo "${{ secrets.BREAKGLASS_SSH_KEY }}" > ~/id_ed25519
          chmod 600 ~/id_ed25519
      - name: Set up the Git configuration
        run: |
          git config --global user.email "abc@example.com"
          git config --global user.name "ABC"
      - name: Merge the Pull Request
        run: |
          PR_NUMBER=${{ github.event.issue.number }}
          PR_REF=$(gh pr view $PR_NUMBER --json headRefName -q '.headRefName')
          git fetch origin main
          git fetch origin refs/pull/$PR_NUMBER/head:$PR_REF
          git checkout main
          git merge --squash origin/$PR_REF
          git commit -m "PR-OK Breakglass squash merge of PR #${{ github.event.issue.number }}"
          git push origin main
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean up
        run: |
          gh pr comment ${{ github.event.issue.number }} -b "The PR has been merged"
          gh pr close ${{ github.event.issue.number }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
