name: Check main branch status
on:
  pull_request:

jobs:
  green-main:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if main is not green
        run: |
          MAIN_STATUS=$(gh run list -b main -L 1 --json status | jq -r '.[0].status')
          echo "Main branch status is $MAIN_STATUS"
          if [ "$MAIN_STATUS" != "completed" ]; then
            exit 1
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
