name: Break glass
on:
  pull_request:

jobs:
  green-main:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if main is not green
        run: |
          MAIN_STATUS=$(gh api repos/$GITHUB_REPOSITORY/commits/main/status | jq -r '.state')
          if [ "$MAIN_STATUS" != "success" ]; then
            exit 1
          fi
